#pragma once

#define MATERIAL_MAX_NUMBER 50
#define MATERIAL_BINDING_POINT 1
#define MATERIAL_USE_DIFFUSE_TEXTURE 1
#define MATERIAL_USE_DIFFUSE_COLOR 2
#define MATERIAL_USE_NORMAL_TEXTURE 4
#define MATERIAL_IS_BUMP_TEXTURE 8
#define MATERIAL_USE_SPECULAR_TEXTURE 16

#define CAMERA_BINDING_POINT 2

#define POINTLIGHT_MAX_NUMBER 50
#define POINTLIGHT_BINDING_POINT 3
#define POINTLIGHT_INDEXES_BINDING_POINT 4