#pragma once

//CONSTANTS//
#define MATERIAL_UBO_BINDING_POINT 1
#define MATERIAL_MAX_NUMBER 50
#define MATERIAL_USE_DIFFUSE_TEXTURE 1
#define MATERIAL_USE_DIFFUSE_COLOR 2
#define MATERIAL_USE_NORMAL_TEXTURE 4
#define MATERIAL_IS_BUMP_TEXTURE 8
#define MATERIAL_USE_SPECULAR_TEXTURE 16

#define CAMERA_UBO_BINDING_POINT 2

#define POINT_LIGHT_UBO_BINDING_POINT 3
#define POINT_LIGHT_MAX_NUMBER 1500

#define DIRECTIONAL_LIGHT_UBO_BINDING_POINT 4
#define DIRECTIONAL_LIGHT_MAX_NUMBER 50

#define USE_LIGHT_CULLING 1
#define CULL_POINT_LIGHT_SSBO_BINDING_POINT 1
#define CULL_POINT_LIGHT_MAX_PER_TILE 512
#define CULL_TILE_SIZE 32

#define CONSTANTS_UBO_BINDING_POINT 6

//LOCATIONS AND BINDINGS//
#define MATERIAL_INDEX_LOCATION 0
#define MVP_MATRIX_LOCATION 1
#define TRANSFORM_MATRIX_LOCATION 2
#define NORMALTOVIEW_MATRIX_LOCATION 3

#define DIFFUSE_TEXTURE_BINDING 0
#define NORMAL_TEXTURE_BINDING 1
#define SPECULAR_TEXTURE_BINDING 2 

#define GBUFFER_NORMAL_TEXTURE_BINDING 3
#define GBUFFER_DEPTH_TEXTURE_BINDING 4